//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Fighting"",
            ""id"": ""656b96ab-e0f4-4cb1-8e5a-694b8fe1db5e"",
            ""actions"": [
                {
                    ""name"": ""SpecialAttack1P1"",
                    ""type"": ""Button"",
                    ""id"": ""1c007cd3-fe1a-4efa-a42c-2d71895e2d54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack1P2"",
                    ""type"": ""Button"",
                    ""id"": ""8b902510-753d-417e-837f-e7859f051917"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack2P1"",
                    ""type"": ""Button"",
                    ""id"": ""10a711b3-94ae-4f57-b4a7-6fba930c1e8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack2P2"",
                    ""type"": ""Button"",
                    ""id"": ""ac00e210-8efc-4720-8211-8df2c8597c95"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack3P1"",
                    ""type"": ""Button"",
                    ""id"": ""302329d8-e657-43d4-82aa-2df525b7326d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack3P2"",
                    ""type"": ""Button"",
                    ""id"": ""47efe8ba-ae1f-4170-9d8b-b5bd65c02c06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack4P1"",
                    ""type"": ""Button"",
                    ""id"": ""30ac61c3-dada-4b6f-92b2-e6208dd52849"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack4P2"",
                    ""type"": ""Button"",
                    ""id"": ""210078a2-0b2b-42a3-8a21-fef1f593f333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicAttack1P1"",
                    ""type"": ""Button"",
                    ""id"": ""1b5e0433-63e2-45d8-bf68-28132e7cb916"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicAttack1P2"",
                    ""type"": ""Button"",
                    ""id"": ""ff9ffd5c-7bde-44aa-a0fb-2824ca164423"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpP1"",
                    ""type"": ""Button"",
                    ""id"": ""a8c0ae4d-35fc-4027-93d2-4fb0f7902f8a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpP2"",
                    ""type"": ""Button"",
                    ""id"": ""da4965b5-56ab-464d-b397-ec719b7d0d02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WalkP1"",
                    ""type"": ""Value"",
                    ""id"": ""fe8870a2-dee5-4b2e-b90a-9820ba232dce"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WalkP2"",
                    ""type"": ""Value"",
                    ""id"": ""f8681d81-0b44-4ac3-a637-dae761e09876"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3064ba27-18e1-4088-87a9-659a29f010db"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack1P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34be9c9d-5288-4630-9642-5c3bd1c81bb3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack2P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8d0a90b-fbbc-426e-994e-c2b46fae1566"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack3P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb7dc97b-ac52-44aa-ab38-1f5ce03a2b97"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack4P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4863e179-4de2-4331-a5ab-811bb859d2e9"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack1P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ccc93d4-ab3d-41e0-aa18-776fbefb0ce5"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack2P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a254eaf3-aa59-433b-9fec-b170174e81d7"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack3P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5cc9279-89f4-4bc1-ab6c-3fccb9290ce9"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAttack4P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9871ccd2-6781-4133-a6cb-7aad0723db78"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BasicAttack1P1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e327464b-30f4-44e6-8d95-64c8350e01df"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BasicAttack1P2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba571a9d-e1d7-4faf-af4a-7eb481b5c22a"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bfb890b-ad70-4a0f-945c-4691b0a5743a"",
                    ""path"": ""<Keyboard>/rightAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""20750d8c-5f82-427d-b21a-8e06ac550553"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkP1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c2468c1f-4a65-4f5f-80b9-efaa0815d980"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""93f332f7-a497-4092-b6ef-610ff106dde1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkP1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""c040c84d-34bb-4a84-bbb6-5331c94edc13"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkP2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5731e0f2-cab1-414d-8e49-fe4b35eb91ac"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""89f5f434-146b-4738-b15c-c8948cef26cc"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkP2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Fighting
        m_Fighting = asset.FindActionMap("Fighting", throwIfNotFound: true);
        m_Fighting_SpecialAttack1P1 = m_Fighting.FindAction("SpecialAttack1P1", throwIfNotFound: true);
        m_Fighting_SpecialAttack1P2 = m_Fighting.FindAction("SpecialAttack1P2", throwIfNotFound: true);
        m_Fighting_SpecialAttack2P1 = m_Fighting.FindAction("SpecialAttack2P1", throwIfNotFound: true);
        m_Fighting_SpecialAttack2P2 = m_Fighting.FindAction("SpecialAttack2P2", throwIfNotFound: true);
        m_Fighting_SpecialAttack3P1 = m_Fighting.FindAction("SpecialAttack3P1", throwIfNotFound: true);
        m_Fighting_SpecialAttack3P2 = m_Fighting.FindAction("SpecialAttack3P2", throwIfNotFound: true);
        m_Fighting_SpecialAttack4P1 = m_Fighting.FindAction("SpecialAttack4P1", throwIfNotFound: true);
        m_Fighting_SpecialAttack4P2 = m_Fighting.FindAction("SpecialAttack4P2", throwIfNotFound: true);
        m_Fighting_BasicAttack1P1 = m_Fighting.FindAction("BasicAttack1P1", throwIfNotFound: true);
        m_Fighting_BasicAttack1P2 = m_Fighting.FindAction("BasicAttack1P2", throwIfNotFound: true);
        m_Fighting_JumpP1 = m_Fighting.FindAction("JumpP1", throwIfNotFound: true);
        m_Fighting_JumpP2 = m_Fighting.FindAction("JumpP2", throwIfNotFound: true);
        m_Fighting_WalkP1 = m_Fighting.FindAction("WalkP1", throwIfNotFound: true);
        m_Fighting_WalkP2 = m_Fighting.FindAction("WalkP2", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_Fighting.enabled, "This will cause a leak and performance issues, Controls.Fighting.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Fighting
    private readonly InputActionMap m_Fighting;
    private List<IFightingActions> m_FightingActionsCallbackInterfaces = new List<IFightingActions>();
    private readonly InputAction m_Fighting_SpecialAttack1P1;
    private readonly InputAction m_Fighting_SpecialAttack1P2;
    private readonly InputAction m_Fighting_SpecialAttack2P1;
    private readonly InputAction m_Fighting_SpecialAttack2P2;
    private readonly InputAction m_Fighting_SpecialAttack3P1;
    private readonly InputAction m_Fighting_SpecialAttack3P2;
    private readonly InputAction m_Fighting_SpecialAttack4P1;
    private readonly InputAction m_Fighting_SpecialAttack4P2;
    private readonly InputAction m_Fighting_BasicAttack1P1;
    private readonly InputAction m_Fighting_BasicAttack1P2;
    private readonly InputAction m_Fighting_JumpP1;
    private readonly InputAction m_Fighting_JumpP2;
    private readonly InputAction m_Fighting_WalkP1;
    private readonly InputAction m_Fighting_WalkP2;
    /// <summary>
    /// Provides access to input actions defined in input action map "Fighting".
    /// </summary>
    public struct FightingActions
    {
        private @Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FightingActions(@Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack1P1".
        /// </summary>
        public InputAction @SpecialAttack1P1 => m_Wrapper.m_Fighting_SpecialAttack1P1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack1P2".
        /// </summary>
        public InputAction @SpecialAttack1P2 => m_Wrapper.m_Fighting_SpecialAttack1P2;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack2P1".
        /// </summary>
        public InputAction @SpecialAttack2P1 => m_Wrapper.m_Fighting_SpecialAttack2P1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack2P2".
        /// </summary>
        public InputAction @SpecialAttack2P2 => m_Wrapper.m_Fighting_SpecialAttack2P2;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack3P1".
        /// </summary>
        public InputAction @SpecialAttack3P1 => m_Wrapper.m_Fighting_SpecialAttack3P1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack3P2".
        /// </summary>
        public InputAction @SpecialAttack3P2 => m_Wrapper.m_Fighting_SpecialAttack3P2;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack4P1".
        /// </summary>
        public InputAction @SpecialAttack4P1 => m_Wrapper.m_Fighting_SpecialAttack4P1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/SpecialAttack4P2".
        /// </summary>
        public InputAction @SpecialAttack4P2 => m_Wrapper.m_Fighting_SpecialAttack4P2;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/BasicAttack1P1".
        /// </summary>
        public InputAction @BasicAttack1P1 => m_Wrapper.m_Fighting_BasicAttack1P1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/BasicAttack1P2".
        /// </summary>
        public InputAction @BasicAttack1P2 => m_Wrapper.m_Fighting_BasicAttack1P2;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/JumpP1".
        /// </summary>
        public InputAction @JumpP1 => m_Wrapper.m_Fighting_JumpP1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/JumpP2".
        /// </summary>
        public InputAction @JumpP2 => m_Wrapper.m_Fighting_JumpP2;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/WalkP1".
        /// </summary>
        public InputAction @WalkP1 => m_Wrapper.m_Fighting_WalkP1;
        /// <summary>
        /// Provides access to the underlying input action "Fighting/WalkP2".
        /// </summary>
        public InputAction @WalkP2 => m_Wrapper.m_Fighting_WalkP2;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Fighting; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FightingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FightingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FightingActions" />
        public void AddCallbacks(IFightingActions instance)
        {
            if (instance == null || m_Wrapper.m_FightingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FightingActionsCallbackInterfaces.Add(instance);
            @SpecialAttack1P1.started += instance.OnSpecialAttack1P1;
            @SpecialAttack1P1.performed += instance.OnSpecialAttack1P1;
            @SpecialAttack1P1.canceled += instance.OnSpecialAttack1P1;
            @SpecialAttack1P2.started += instance.OnSpecialAttack1P2;
            @SpecialAttack1P2.performed += instance.OnSpecialAttack1P2;
            @SpecialAttack1P2.canceled += instance.OnSpecialAttack1P2;
            @SpecialAttack2P1.started += instance.OnSpecialAttack2P1;
            @SpecialAttack2P1.performed += instance.OnSpecialAttack2P1;
            @SpecialAttack2P1.canceled += instance.OnSpecialAttack2P1;
            @SpecialAttack2P2.started += instance.OnSpecialAttack2P2;
            @SpecialAttack2P2.performed += instance.OnSpecialAttack2P2;
            @SpecialAttack2P2.canceled += instance.OnSpecialAttack2P2;
            @SpecialAttack3P1.started += instance.OnSpecialAttack3P1;
            @SpecialAttack3P1.performed += instance.OnSpecialAttack3P1;
            @SpecialAttack3P1.canceled += instance.OnSpecialAttack3P1;
            @SpecialAttack3P2.started += instance.OnSpecialAttack3P2;
            @SpecialAttack3P2.performed += instance.OnSpecialAttack3P2;
            @SpecialAttack3P2.canceled += instance.OnSpecialAttack3P2;
            @SpecialAttack4P1.started += instance.OnSpecialAttack4P1;
            @SpecialAttack4P1.performed += instance.OnSpecialAttack4P1;
            @SpecialAttack4P1.canceled += instance.OnSpecialAttack4P1;
            @SpecialAttack4P2.started += instance.OnSpecialAttack4P2;
            @SpecialAttack4P2.performed += instance.OnSpecialAttack4P2;
            @SpecialAttack4P2.canceled += instance.OnSpecialAttack4P2;
            @BasicAttack1P1.started += instance.OnBasicAttack1P1;
            @BasicAttack1P1.performed += instance.OnBasicAttack1P1;
            @BasicAttack1P1.canceled += instance.OnBasicAttack1P1;
            @BasicAttack1P2.started += instance.OnBasicAttack1P2;
            @BasicAttack1P2.performed += instance.OnBasicAttack1P2;
            @BasicAttack1P2.canceled += instance.OnBasicAttack1P2;
            @JumpP1.started += instance.OnJumpP1;
            @JumpP1.performed += instance.OnJumpP1;
            @JumpP1.canceled += instance.OnJumpP1;
            @JumpP2.started += instance.OnJumpP2;
            @JumpP2.performed += instance.OnJumpP2;
            @JumpP2.canceled += instance.OnJumpP2;
            @WalkP1.started += instance.OnWalkP1;
            @WalkP1.performed += instance.OnWalkP1;
            @WalkP1.canceled += instance.OnWalkP1;
            @WalkP2.started += instance.OnWalkP2;
            @WalkP2.performed += instance.OnWalkP2;
            @WalkP2.canceled += instance.OnWalkP2;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FightingActions" />
        private void UnregisterCallbacks(IFightingActions instance)
        {
            @SpecialAttack1P1.started -= instance.OnSpecialAttack1P1;
            @SpecialAttack1P1.performed -= instance.OnSpecialAttack1P1;
            @SpecialAttack1P1.canceled -= instance.OnSpecialAttack1P1;
            @SpecialAttack1P2.started -= instance.OnSpecialAttack1P2;
            @SpecialAttack1P2.performed -= instance.OnSpecialAttack1P2;
            @SpecialAttack1P2.canceled -= instance.OnSpecialAttack1P2;
            @SpecialAttack2P1.started -= instance.OnSpecialAttack2P1;
            @SpecialAttack2P1.performed -= instance.OnSpecialAttack2P1;
            @SpecialAttack2P1.canceled -= instance.OnSpecialAttack2P1;
            @SpecialAttack2P2.started -= instance.OnSpecialAttack2P2;
            @SpecialAttack2P2.performed -= instance.OnSpecialAttack2P2;
            @SpecialAttack2P2.canceled -= instance.OnSpecialAttack2P2;
            @SpecialAttack3P1.started -= instance.OnSpecialAttack3P1;
            @SpecialAttack3P1.performed -= instance.OnSpecialAttack3P1;
            @SpecialAttack3P1.canceled -= instance.OnSpecialAttack3P1;
            @SpecialAttack3P2.started -= instance.OnSpecialAttack3P2;
            @SpecialAttack3P2.performed -= instance.OnSpecialAttack3P2;
            @SpecialAttack3P2.canceled -= instance.OnSpecialAttack3P2;
            @SpecialAttack4P1.started -= instance.OnSpecialAttack4P1;
            @SpecialAttack4P1.performed -= instance.OnSpecialAttack4P1;
            @SpecialAttack4P1.canceled -= instance.OnSpecialAttack4P1;
            @SpecialAttack4P2.started -= instance.OnSpecialAttack4P2;
            @SpecialAttack4P2.performed -= instance.OnSpecialAttack4P2;
            @SpecialAttack4P2.canceled -= instance.OnSpecialAttack4P2;
            @BasicAttack1P1.started -= instance.OnBasicAttack1P1;
            @BasicAttack1P1.performed -= instance.OnBasicAttack1P1;
            @BasicAttack1P1.canceled -= instance.OnBasicAttack1P1;
            @BasicAttack1P2.started -= instance.OnBasicAttack1P2;
            @BasicAttack1P2.performed -= instance.OnBasicAttack1P2;
            @BasicAttack1P2.canceled -= instance.OnBasicAttack1P2;
            @JumpP1.started -= instance.OnJumpP1;
            @JumpP1.performed -= instance.OnJumpP1;
            @JumpP1.canceled -= instance.OnJumpP1;
            @JumpP2.started -= instance.OnJumpP2;
            @JumpP2.performed -= instance.OnJumpP2;
            @JumpP2.canceled -= instance.OnJumpP2;
            @WalkP1.started -= instance.OnWalkP1;
            @WalkP1.performed -= instance.OnWalkP1;
            @WalkP1.canceled -= instance.OnWalkP1;
            @WalkP2.started -= instance.OnWalkP2;
            @WalkP2.performed -= instance.OnWalkP2;
            @WalkP2.canceled -= instance.OnWalkP2;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FightingActions.UnregisterCallbacks(IFightingActions)" />.
        /// </summary>
        /// <seealso cref="FightingActions.UnregisterCallbacks(IFightingActions)" />
        public void RemoveCallbacks(IFightingActions instance)
        {
            if (m_Wrapper.m_FightingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FightingActions.AddCallbacks(IFightingActions)" />
        /// <seealso cref="FightingActions.RemoveCallbacks(IFightingActions)" />
        /// <seealso cref="FightingActions.UnregisterCallbacks(IFightingActions)" />
        public void SetCallbacks(IFightingActions instance)
        {
            foreach (var item in m_Wrapper.m_FightingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FightingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FightingActions" /> instance referencing this action map.
    /// </summary>
    public FightingActions @Fighting => new FightingActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Fighting" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FightingActions.AddCallbacks(IFightingActions)" />
    /// <seealso cref="FightingActions.RemoveCallbacks(IFightingActions)" />
    public interface IFightingActions
    {
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack1P1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack1P1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack1P2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack1P2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack2P1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack2P1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack2P2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack2P2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack3P1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack3P1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack3P2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack3P2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack4P1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack4P1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpecialAttack4P2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpecialAttack4P2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BasicAttack1P1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBasicAttack1P1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BasicAttack1P2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBasicAttack1P2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpP1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpP1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpP2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpP2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WalkP1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWalkP1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WalkP2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWalkP2(InputAction.CallbackContext context);
    }
}
